import type { AppLocale } from "@/config/i18n";

/** Provider contract. To switch from DeepL, implement this and register it in index.ts. */
export interface Translator {
  readonly name: string;
  /** Translates every text; returns an array of the same length and in the same order. */
  translate(texts: string[], from: AppLocale, to: AppLocale): Promise<string[]>;
}

/** Error whose message is safe to show in the admin panel. */
export class TranslationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TranslationError";
  }
}

/**
 * machine: generated by the provider, refreshed automatically when the source changes.
 * manual: corrected by an admin, never overwritten unless the admin asks to retranslate.
 */
export const translationSources = ["machine", "manual"] as const;

export type TranslationSource = (typeof translationSources)[number];

export type TranslationMeta = {
  source: TranslationSource;
  /** Hash of the source content this translation was generated from or reviewed against. */
  sourceHash: string;
  /** Last machine translation (unchanged by manual edits). */
  translatedAt: string | null;
};

export type TranslationStatus = "missing" | "machine" | "machine-stale" | "manual" | "manual-stale";

export type TranslationSyncResult = "translated" | "up-to-date" | "manual" | "not-configured";
